services:
  mysql:
    image: mysql:8.0
    container_name: tfg_mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - tfg-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: tfg_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8100:80"
    depends_on:
      - mysql
    networks:
      - tfg-network

volumes:
  mysql_data:

networks:
  tfg-network:
    driver: bridge
